spring:
  application:
    consume:
      msclient:
        url: http://localhost:8081/client
  data:
    mongodb:
      authentication-database: admin
      database: tarjetas
      host: localhost
      password: mongo_pass
      port: 27017
      username: mongo_user
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
