server:
  port: 8083
spring:
  application:
    consume:
      msdebitcard:
        url: http://localhost:8082/debitcard

  data:
    mongodb:
      authentication-database: admin
      database: mstransaction
      host: localhost
      password: mongo_pass
      port: 27017
      username: mongo_user
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer